# -*- coding: utf-8 -*-
"""TH_DEEP_LAB01_ANN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lFd3pgKoMtEvWqAsEkEPDiyJJPHV3imT
"""

#Thêm thư viện cần thiết

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, LabelEncoder

#bài1

# 1. NẠP DỮ LIỆU MNIST (không có CIFAR10 nên dùng ké MNIST)
print("Đang nạp dữ liệu MNIST...")
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()

# Chuẩn hóa dữ liệu (Feature scaling) về khoảng [0, 1]
X_train = X_train.astype('float32') / 255.0
X_test = X_test.astype('float32') / 255.0

# 2. XÂY DỰNG KIẾN TRÚC ANN
# Một mô hình ANN gồm các tầng Fully Connected (Dense)
model = Sequential([
    # Input Layer: Duỗi ảnh 28x28 thành vector 784 phần tử[cite: 3]
    Flatten(input_shape=(28, 28)),

    # Hidden Layer 1: 256 neuron, dùng ReLU để học mẫu phi tuyến tính[cite: 3]
    Dense(256, activation='relu', kernel_initializer='uniform'),

    # Dropout: Ngẫu nhiên gán vài weight bằng 0 (rate 0.2) để tránh Overfitting[cite: 3]
    Dropout(0.2),

    # Hidden Layer 2: 128 neuron
    Dense(128, activation='relu', kernel_initializer='uniform'),

    # Output Layer: 10 neuron cho 10 chữ số (0-9).
    # Dùng Softmax để tính xác suất cho các label đầu ra[cite: 3].
    Dense(10, activation='softmax')
])

# 3. BIÊN DỊCH MÔ HÌNH[cite: 3]
# Loss function: sparse_categorical_crossentropy (đo lường hiệu quả học)[cite: 3]
# Optimizer: adam (cải tiến quá trình học bằng cách cập nhật weight)[cite: 3]
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# 4. HUẤN LUYỆN (Training)[cite: 3]
print("Bắt đầu huấn luyện...")
history = model.fit(X_train, y_train, validation_split=0.1, epochs=10, batch_size=32)

# 5. ĐÁNH GIÁ (Evaluation)[cite: 3]
loss, acc = model.evaluate(X_test, y_test)
print(f"\nĐộ chính xác trên tập Test: {acc*100:.2f}%")

# 6. DỰ BÁO ẢNH MỚI[cite: 3]
prediction = model.predict(X_test)
print(f"Dự đoán ảnh đầu tiên là số: {np.argmax(prediction[0])}")
print(f"Thực tế là số: {y_test[0]}")

#bài2

# 1. Tải bộ dữ liệu MNIST
mnist = tf.keras.datasets.mnist
(X_train_mn, y_train_mn), (X_test_mn, y_test_mn) = mnist.load_data()

# Chuẩn hóa dữ liệu
X_train_mn = X_train_mn / 255.0
X_test_mn = X_test_mn / 255.0

# 2. Khởi tạo mô hình
model_mnist = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(256, activation='relu', kernel_initializer='uniform'),
    Dropout(0.2),
    Dense(128, activation='relu', kernel_initializer='uniform'),
    Dense(10, activation='softmax')
])

# 3. Biên dịch và huấn luyện
model_mnist.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model_mnist.fit(X_train_mn, y_train_mn, epochs=10, validation_split=0.1, batch_size=32)

#bài3

import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np
import os
from numpy import asarray, save, load
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout
from sklearn.model_selection import train_test_split

# =================================================================
# 1. NẠP DỮ LIỆU TỪ TFDS
# =================================================================
print("--- Đang tải dữ liệu cats_vs_dogs từ TFDS ---")
# Lưu ý: TFDS sẽ tự động tải dữ liệu từ server của Microsoft/Google
try:
    # Chỉ lấy 10% dữ liệu (khoảng 2300 ảnh) để chạy nhanh và tránh tràn RAM Colab
    dataset, info = tfds.load('cats_vs_dogs', split='train[:10%]', with_info=True, as_supervised=True)
    print("Tải dữ liệu thành công!")
except Exception as e:
    print(f"Lỗi tải dữ liệu: {e}")
    print("Nếu vẫn gặp lỗi 403/Forbidden, server chứa dataset này có thể đang bảo trì.")

# =================================================================
# 2. TIỀN XỬ LÝ & LƯU .NPY (Đúng quy trình Lab 3)
# =================================================================
photos, labels = list(), list()

print("--- Đang chuẩn bị mảng ảnh (200x200) ---")
for image, label in dataset:
    # Resize ảnh về 200x200 theo yêu cầu bài thực hành
    image_resized = tf.image.resize(image, (200, 200))
    # Chuyển tensor sang mảng numpy
    photos.append(image_resized.numpy())
    labels.append(float(label.numpy()))

# Chuyển thành mảng Numpy cuối cùng
photos = asarray(photos)
labels = asarray(labels)

# Lưu trữ dữ liệu để sử dụng sau này[cite: 3]
save('dogs_vs_cats_photos.npy', photos)
save('dogs_vs_cats_labels.npy', labels)
print(f"Đã lưu file .npy thành công. Kích thước: {photos.shape}")

# =================================================================
# 3. HUẤN LUYỆN MẠNG ANN[cite: 3]
# =================================================================
# Nạp lại dữ liệu từ file .npy[cite: 3]
X = load('dogs_vs_cats_photos.npy').astype('float32') / 255.0 # Chuẩn hóa pixel[cite: 3]
y = load('dogs_vs_cats_labels.npy')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Xây dựng kiến trúc Layer: Input -> Hidden -> Output[cite: 3]
model = Sequential([
    Flatten(input_shape=(200, 200, 3)), # Tầng Input duỗi ảnh thành vector[cite: 3]

    # Tầng Hidden dùng ReLU (gán 0 cho các giá trị âm)[cite: 3]
    Dense(128, activation='relu', kernel_initializer='uniform'),
    Dropout(0.5), # Kỹ thuật Dropout để ngăn chặn Overfitting[cite: 3]

    Dense(64, activation='relu', kernel_initializer='uniform'),

    # Tầng Output dùng Sigmoid cho bài toán phân loại nhị phân[cite: 3]
    Dense(1, activation='sigmoid')
])

# Biên dịch mô hình[cite: 3]
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

print("--- Bắt đầu huấn luyện mạng ANN ---")
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

# Đánh giá hiệu quả (Loss function)[cite: 3]
loss, acc = model.evaluate(X_test, y_test)
print(f"\nĐộ chính xác trên tập Test: {acc*100:.2f}%")

#bài4

# Tải bộ dữ liệu Adult từ kho lưu trữ UCI
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data -O adult.csv

# Giả sử file dữ liệu tên là 'adult.csv'
df_adult = pd.read_csv('adult.csv')

# Điền dữ liệu thiếu và Label Encode cho các cột chứa text (chuỗi)
le = LabelEncoder()
for col in df_adult.columns:
    if df_adult[col].dtype == 'object':
        df_adult[col] = le.fit_transform(df_adult[col].astype(str))

# Tách Features (X) và Label (y) - Giả sử cột cuối cùng là thu nhập
X_adult = df_adult.iloc[:, :-1].values
y_adult = df_adult.iloc[:, -1].values

# Feature Scaling bằng MinMaxScaler[cite: 3]
scaler = MinMaxScaler()
X_adult = scaler.fit_transform(X_adult)

X_train_ad, X_test_ad, y_train_ad, y_test_ad = train_test_split(X_adult, y_adult, test_size=0.2)

# Xây dựng mô hình ANN
model_adult = Sequential([
    Dense(64, activation='relu', input_dim=X_train_ad.shape[1]),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid') # Phân lớp nhị phân >50K hoặc <=50K[cite: 3]
])

model_adult.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model_adult.fit(X_train_ad, y_train_ad, epochs=20, batch_size=32, validation_split=0.1)

#bài5

# Tải bộ dữ liệu Car từ kho lưu trữ UCI
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data -O car.csv

# Giả sử file tên là 'car.csv'
df_car = pd.read_csv('car.csv')

le_car = LabelEncoder()
for col in df_car.columns:
    df_car[col] = le_car.fit_transform(df_car[col].astype(str))

X_car = df_car.iloc[:, :-1].values
y_car = df_car.iloc[:, -1].values

# Đếm số lượng class đầu ra
num_classes = len(np.unique(y_car))

X_train_car, X_test_car, y_train_car, y_test_car = train_test_split(X_car, y_car, test_size=0.2)

model_car = Sequential([
    Dense(64, activation='relu', input_dim=X_train_car.shape[1]),
    Dense(32, activation='relu'),
    Dense(num_classes, activation='softmax') # Dùng Softmax cho đa phân lớp[cite: 3]
])

model_car.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model_car.fit(X_train_car, y_train_car, epochs=30, batch_size=16)