# -*- coding: utf-8 -*-
"""TH_DEEP_LAB01_Tensorflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YjCcKIAA-XwR3gl6E0Itdxkk2wAJKr9w
"""

#Thêm thư viện

import tensorflow as tf
import numpy as np

#bai1

t1 = tf.zeros([2, 3])
print("Bài 1:\n", t1)

#bai2

X = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.zeros_like(X)
print("Bài 2:\n", t2)

#bai3

t3 = tf.fill([3, 2], 5)
print("Bài 3:\n", t3)

#bai4

t4 = tf.linspace(10.0, 12.0, 3, name="linspace")
print("Bài 4:\n", t4)

#bai5

t5 = tf.range(10, 102, delta=2)
print("Bài 5:\n", t5)

#bai6

t6 = tf.random.normal([3, 2], mean=0.0, stddev=2.0)
print("Bài 6:\n", t6)

#bai7

t7 = tf.random.uniform([3, 2], minval=0.0, maxval=2.0)
print("Bài 7:\n", t7)

#bai8

X_8 = tf.constant([[1, 2], [3, 4], [5, 6]])
t8 = tf.random.shuffle(X_8)
print("Bài 8:\n", t8)

#bai9

t9_origin = tf.random.normal([10, 10, 3])
t9_cropped = tf.image.random_crop(t9_origin, size=[5, 5, 3])
print("Bài 9 (Kích thước sau khi crop):", t9_cropped.shape)

#bai10

x10 = tf.random.uniform([5], minval=1, maxval=10)
y10 = tf.random.uniform([5], minval=1, maxval=10)

print("x =", x10.numpy())
print("y =", y10.numpy())

# Sử dụng tf.where để kiểm tra điều kiện x < y
t10 = tf.where(x10 < y10, x10 + y10, x10 - y10)
print("Bài 10:\n", t10.numpy())

#bai11

x11 = tf.random.uniform([3, 2], minval=5.0, maxval=10.0)
y11 = tf.random.uniform([2, 3], minval=15.0, maxval=20.0)

# Giữ lại đường chéo của x (xóa các phần tử không thuộc đường chéo chính)
x_diag = tf.linalg.band_part(x11, 0, 0)

# Chuyển vị y thành (3, 2) để có thể cộng với x
y_transpose = tf.transpose(y11)

t11 = x_diag + y_transpose
print("Bài 11:\n", t11.numpy())

#bai12

@tf.function
def compute_ops(x, y):
    return tf.add(x, y), tf.subtract(x, y), tf.multiply(x, y), tf.divide(x, y)

x12 = tf.random.normal([3, 2, 2])
y12 = tf.random.normal([3, 2, 2])

add_res, sub_res, mul_res, div_res = compute_ops(x12, y12)
print("Bài 12 thực thi graph thành công!")

#bai13

class SumModel(tf.Module):
    @tf.function
    def __call__(self, x, y):
        return x + y

model_13 = SumModel()
print("Bài 13:", model_13(tf.constant(5), tf.constant(10)).numpy())

#bai14

class DiffProdModel(tf.Module):
    @tf.function
    def __call__(self, x, y):
        return x - y, x * y

model_14 = DiffProdModel()
diff, prod = model_14(tf.constant(8), tf.constant(3))
print("Bài 14 - Hiệu:", diff.numpy(), "Tích:", prod.numpy())

#bai15

class RectanglePerimeter(tf.Module):
    @tf.function
    def __call__(self, a, b):
        return (a + b) * 2

model_15 = RectanglePerimeter()
print("Bài 15 (a=3, b=4):", model_15(tf.constant(3), tf.constant(4)).numpy())

#bai16

class BoxSurfaceArea(tf.Module):
    @tf.function
    def __call__(self, a, b, c):
        s_xq = (a + b) * c * 2
        s_tp = (a * b) * 2 + s_xq
        return s_tp

model_16 = BoxSurfaceArea()
print("Bài 16 (a=2, b=3, c=4):", model_16(tf.constant(2), tf.constant(3), tf.constant(4)).numpy())

#bai17

class TrapezoidParallelProof(tf.Module):
    @tf.function
    def __call__(self, AD, BC, AB, CD):
        cond1 = tf.equal(AD, BC)
        cond2 = tf.equal(AB, CD)
        # Trả về True nếu cả 2 điều kiện đều đúng
        return tf.logical_and(cond1, cond2)

model_17 = TrapezoidParallelProof()
print("Bài 17:", model_17(tf.constant(5), tf.constant(5), tf.constant(10), tf.constant(10)).numpy())

#bai18

class TrapezoidBaseProof(tf.Module):
    @tf.function
    def __call__(self, AD, BC, is_parallel):
        cond1 = tf.equal(AD, BC)
        return tf.logical_and(cond1, is_parallel)

model_18 = TrapezoidBaseProof()
print("Bài 18:", model_18(tf.constant(4), tf.constant(4), tf.constant(True)).numpy())

#bai19

class TriangleMidsegmentProof(tf.Module):
    @tf.function
    def __call__(self, AM, MB, MN, BC):
        # Đường trung bình cần thỏa mãn MN = BC/2
        cond1 = tf.equal(AM, MB)
        cond2 = tf.equal(MN, BC / 2.0)

        return tf.logical_and(cond1, cond2)

model_19 = TriangleMidsegmentProof()
print("Bài 19:", model_19(tf.constant(3.0), tf.constant(3.0), tf.constant(5.0), tf.constant(10.0)).numpy())