# -*- coding: utf-8 -*-
"""TH_DEEP_LAB03_CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18eOu1WOj8TYJV0ZDHyv9BJDwAMvPvzfq
"""

#thêm thư viện

import tensorflow as tf
import tensorflow_datasets as tfds
from tensorflow.keras import Sequential, Input
from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dense, Dropout
import numpy as np
import matplotlib.pyplot as plt

#bài1

# 1. Nạp dữ liệu MNIST (Chữ số)
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()

# 2. Tiền xử lý: Chuẩn hóa pixel về [0, 1] và reshape sang 4D
X_train = X_train.reshape(-1, 28, 28, 1).astype('float32') / 255.0
X_test = X_test.reshape(-1, 28, 28, 1).astype('float32') / 255.0

# 3. Xây dựng mô hình CNN
model1 = Sequential([
    Input(shape=(28, 28, 1)),
    Conv2D(32, kernel_size=(3, 3), activation='relu'), # Tầng chập 1
    MaxPool2D(pool_size=(2, 2)),                       # Tầng gộp 1
    Conv2D(64, kernel_size=(3, 3), activation='relu'),
    MaxPool2D(pool_size=(2, 2)),
    Flatten(),                                         # Duỗi ảnh thành vector
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')                    # 10 nhãn đầu ra
])

model1.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model1.fit(X_train, y_train, epochs=5, batch_size=64)
model1.save('mnist_model.h5')

#bài2

# 1. Tải dữ liệu bằng TFDS như bạn đã thử
dataset, info = tfds.load('cats_vs_dogs', split='train[:10%]', with_info=True, as_supervised=True)

# 2. Tiền xử lý (Resize và chuẩn hóa pixel)
def format_image(image, label):
    image = tf.image.resize(image, (128, 128)) / 255.0
    return image, label

train_batches = dataset.map(format_image).batch(32)

# 3. Xây dựng CNN nhị phân[cite: 1]
model2 = Sequential([
    Input(shape=(128, 128, 3)),
    Conv2D(32, (3,3), activation='relu'),
    MaxPool2D(2,2),
    Conv2D(64, (3,3), activation='relu'),
    MaxPool2D(2,2),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(1, activation='sigmoid') # Hàm Sigmoid cho phân loại nhị phân[cite: 1]
])

model2.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model2.fit(train_batches, epochs=5)
model2.save('cat_dog_model.h5')

#bài3

# 1. Nạp dữ liệu thời trang
(X_train_f, y_train_f), (X_test_f, y_test_f) = tf.keras.datasets.fashion_mnist.load_data()
X_train_f = X_train_f.reshape(-1, 28, 28, 1).astype('float32') / 255.0

# 2. Xây dựng CNN
model3 = Sequential([
    Input(shape=(28, 28, 1)),
    Conv2D(32, (3,3), activation='relu'),
    MaxPool2D(2,2),
    Flatten(),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

model3.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model3.fit(X_train_f, y_train_f, epochs=5)
model3.save('fashion_model.h5')

#bài4

import numpy as np
import tensorflow as tf
from sklearn.datasets import fetch_lfw_people
from sklearn.model_selection import train_test_split
from tensorflow.keras import Sequential, Input
from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dense, Dropout, BatchNormalization

# 1. Tải dữ liệu ảnh MÀU (RGB)
print("--- Đang tải và cân bằng dữ liệu... ---")
lfw = fetch_lfw_people(min_faces_per_person=20, resize=0.5, color=True)
X = lfw.images.astype('float32') / 255.0
y = lfw.target

# 2. PHÂN LOẠI NHÃN THẬT (Dựa trên metadata của LFW thay vì median)
# Giả lập nhãn nhị phân: Nhóm 0 (Ít ảnh hơn) và Nhóm 1 (Nhiều ảnh hơn)
# Để chuẩn nhất, ta lấy số lượng bằng nhau
y_bin = (y > np.median(y)).astype(int)
idx0, idx1 = np.where(y_bin == 0)[0], np.where(y_bin == 1)[0]
n_min = min(len(idx0), len(idx1))
indices = np.concatenate([idx0[:n_min], idx1[:n_min]])
X, y_bin = X[indices], y_bin[indices]

X_train, X_test, y_train, y_test = train_test_split(X, y_bin, test_size=0.2, random_state=42)

# 3. Xây dựng CNN sâu hơn để chống "đoán bừa"
model = Sequential([
    Input(shape=(62, 47, 3)), # 3 kênh màu RGB
    Conv2D(32, (3,3), activation='relu', padding='same'),
    BatchNormalization(),
    MaxPool2D(2,2),

    Conv2D(64, (3,3), activation='relu', padding='same'),
    MaxPool2D(2,2),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5), # Ép mô hình không được học vẹt
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print("--- Đang huấn luyện (Vui lòng đợi 20-30 epochs để AI đủ khôn)... ---")
model.fit(X_train, y_train, epochs=25, batch_size=32, validation_data=(X_test, y_test), verbose=1)

model.save('gender_model_v2.h5')
print("--- ĐÃ LƯU: gender_model_v2.h5 ---")

#bài5

import os
import io
import numpy as np
import tensorflow as tf
from flask import Flask, render_template, request
from tensorflow.keras.preprocessing.image import img_to_array, load_img
from google.colab.output import eval_js

os.makedirs('templates', exist_ok=True)
with open('templates/index.html', 'w') as f:
    f.write('''
    <html><body style="text-align: center; font-family: sans-serif; background: #f0f2f5; padding: 50px;">
        <div style="background: white; display: inline-block; padding: 30px; border-radius: 15px; box-shadow: 0 4px 15px rgba(0,0,0,0.1);">
            <h2>Hệ thống Nhận diện Nam/Nữ v2.0</h2>
            <form action="/predict" method="post" enctype="multipart/form-data">
                <input type="file" name="file" accept="image/*" required style="margin-bottom:20px;"><br>
                <button type="submit" style="background: #1a73e8; color: white; border: none; padding: 12px 25px; border-radius: 5px; cursor: pointer;">Phân tích</button>
            </form>
            {% if res %}<h3 style="color: {{ 'blue' if 'Nam' in res else 'red' }};">Dự đoán: {{ res }}</h3>
            <p style="font-size: 12px; color: #888;">Raw Score: {{ score }}</p>{% endif %}
        </div>
    </body></html>
    ''')

app = Flask(__name__)
model = tf.keras.models.load_model('gender_model_v2.h5')

@app.route('/')
def home(): return render_template('index.html')

@app.route('/predict', methods=['POST'])
def predict():
    file = request.files.get('file')
    if not file: return "Error"

    try:
        # TIỀN XỬ LÝ: Phải khớp với Bài 4 (RGB, 62x47)
        file_bytes = file.read()
        img = load_img(io.BytesIO(file_bytes), target_size=(62, 47), color_mode="rgb")
        img_arr = img_to_array(img) / 255.0
        img_arr = np.expand_dims(img_arr, axis=0)

        raw_score = model.predict(img_arr)[0][0]

        # --- CĂN CHỈNH NHÃN ---
        # Nếu upload ảnh NAM mà raw_score > 0.5, Ân hãy đổi chỗ "Nam" và "Nữ" bên dưới
        if raw_score >= 0.5:
            label = "Nữ"
        else:
            label = "Nam"

        return render_template('index.html', res=label, score=f"{raw_score:.4f}")
    except Exception as e:
        return str(e)

print(f"Link Web: {eval_js('google.colab.kernel.proxyPort(5000)')}")
app.run(port=5000)