# -*- coding: utf-8 -*-
"""TH_DEEP_LAB01_NumPy_Pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJGZ1tA11priLYWbUy_8qiJTfKat53k-
"""

#Thêm thư viện cần thiết
import numpy as np
import torch

#bai_1

# Tạo mảng 3x3 với giá trị từ 0 đến 20
arr1 = np.random.randint(0, 21, size=(3, 3))
print("Mảng 1:\n", arr1)

# Kiểm tra tất cả các phần tử có khác 0 hay không
is_all_nonzero = np.all(arr1 != 0)
print("Tất cả phần tử khác 0:", is_all_nonzero)

#bai2

arr2 = np.random.randint(0, 21, size=(3, 3))
print("Mảng 2:\n", arr2)

is_any_nonzero = np.any(arr2 != 0)
print("Tồn tại phần tử khác 0:", is_any_nonzero)

#bai3

# Mảng 1 chiều
x1 = np.array([1, 5, 10])
y1 = np.array([2, 5, 8])
print("So sánh 1 chiều (x1 > y1):", np.greater(x1, y1))
print("So sánh 1 chiều (x1 <= y1):", np.less_equal(x1, y1))

# Mảng 2 chiều
x2 = np.array([[1, 2], [3, 4]])
y2 = np.array([[1, 3], [2, 4]])
print("So sánh 2 chiều (x2 >= y2):\n", np.greater_equal(x2, y2))
print("So sánh 2 chiều (x2 < y2):\n", np.less(x2, y2))

#bai4

arr4 = np.concatenate([np.ones(10), np.zeros(10), np.ones(10) * 5])
print("Mảng kết quả:\n", arr4)

#bai5

arr5 = np.arange(30, 71, 2)
print("Mảng số chẵn:\n", arr5)

#bai6

arr6 = np.identity(3)
print("Ma trận đơn vị 3x3:\n", arr6)

#bai7

arr7 = np.random.randint(15, 56, size=10)
print("Mảng ban đầu:", arr7)
print("Bỏ phần tử đầu và cuối:", arr7[1:-1])

#bai8

arr8 = np.random.randint(0, 21, size=20)
print("Mảng ban đầu:\n", arr8)

# Lọc và đổi dấu
arr8[(arr8 >= 9) & (arr8 <= 15)] *= -1
print("Mảng sau khi đổi dấu:\n", arr8)

#bai9

arr9 = np.random.randint(10, 22, size=(3, 4))
print("Ma trận 3x4:\n", arr9)

#bai10

arr10 = np.ones((10, 10))
arr10[1:-1, 1:-1] = 0
print("Ma trận 10x10:\n", arr10)

#bai11

arr11 = np.diag([1, 2, 3, 4, 5])
print("Ma trận đường chéo:\n", arr11)

#bai12

arr12 = np.random.randint(1, 10, size=(3, 3, 3))
print("Tổng theo cột (axis=0):\n", np.sum(arr12, axis=0))
print("Tổng theo dòng (axis=1):\n", np.sum(arr12, axis=1))

#bai13

v1 = np.random.randint(1, 10, 10)
v2 = np.random.randint(1, 10, 10)
print("Vector 1:", v1)
print("Vector 2:", v2)
print("Inner product:", np.dot(v1, v2))

#bai14

A = np.random.randint(1, 10, size=(4, 3))
y = np.random.randint(1, 10, size=3)
print("Ma trận A:\n", A)
print("Vector y:", y)
print("Kết quả A + y:\n", A + y)

#bai15

s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])

print("Cộng:\n", s1 + s2)
print("Trừ:\n", s1 - s2)
print("Nhân:\n", s1 * s2)
print("Chia:\n", s1 / s2)

#bai16

df16 = pd.DataFrame({'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1, 11]})
first_col_series = df16.iloc[:, 0]
print("Cột đầu tiên dưới dạng Series:\n", first_col_series)

#bai17

df17 = pd.DataFrame(np.random.randint(1, 20, size=(4, 3)), columns=['A', 'B', 'C'])
print("DataFrame gốc:\n", df17)
print("Sắp xếp theo cột 'B':\n", df17.sort_values(by='B'))

#bai18

s18 = pd.Series([1, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E'])
s18_reindexed = s18.reindex(['B', 'A', 'C', 'D', 'E'])
print("Series sau khi đổi thứ tự index:\n", s18_reindexed)

#bai19

x = pd.Series([1, 2, 3, 4, 5])
y = pd.Series([2, 4, 6, 8, 10])
result19 = x[~x.isin(y)]
print("Các phần tử trong x nhưng không có trong y:\n", result19)

#bai20

x20 = pd.Series(np.random.randint(1, 30, 20))
y20 = pd.Series(np.random.randint(1, 30, 20))

print("Giao (intersect1d):", np.intersect1d(x20, y20))
print("Hội (union1d):", np.union1d(x20, y20))

#bai21

sx = pd.Series(['p', 'q', 'r', 'x', 'y'], index=[0, 1, 2, 8, 9])
sy = pd.Series(['a', 'b'], index=[3, 4])

# Theo chiều dọc
vertical = pd.concat([sx, sy], axis=0)
print("Chiều dọc:\n", vertical)

# Theo chiều ngang
horizontal = pd.concat([sx, sy], axis=1)
print("Chiều ngang:\n", horizontal)

#bai22

exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df_exam = pd.DataFrame(exam_data, index=labels)
print(df_exam)

#bai23

print(df_exam.head(3))

#bai24

print(df_exam[['name', 'score']])

#bai25

print(df_exam[df_exam['attempts'] > 2])

#bai26

print("Số dòng, số cột:", df_exam.shape)

#bai27

print(df_exam[df_exam['score'].isnull()])

#bai28

print(df_exam[df_exam['score'].between(15, 20)])

#bai29

condition = (df_exam['attempts'] > 2) & (df_exam['score'].between(15, 20))
print(df_exam[condition])

#bai30

df_exam.loc['d', 'score'] = 19.0
print(df_exam)